apiVersion: x.getambassador.io/v3alpha1
kind:  AmbassadorMapping
metadata:
  name:  rollout-demo-mapping
spec:
  hostname: '*'
  resolver: endpoint
  prefix: /rollout-demo
  rewrite: /echo
  service: rollout-demo:80
