apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 879b546b-5a5e-43d6-911f-e0a9507f82ce
  creationTimestamp: null
  name: rollout-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rollout-demo
  strategy:
    canary:
      canaryService: rollout-demo-canary
      stableService: rollout-demo
      steps:
      - setWeight: 10
      - pause:
          duration: 12
      - setWeight: 20
      - pause:
          duration: 12
      - setWeight: 30
      - pause:
          duration: 12
      - setWeight: 40
      - pause:
          duration: 12
      - setWeight: 50
      - pause:
          duration: 12
      - setWeight: 60
      - pause:
          duration: 12
      - setWeight: 70
      - pause:
          duration: 12
      - setWeight: 80
      - pause:
          duration: 12
      - setWeight: 90
      - pause:
          duration: 12
      - setWeight: 100
      - pause:
          duration: 12
      trafficRouting:
        ambassador:
          mappings:
          - rollout-demo-mapping
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-demo
    spec:
      containers:
      - image: alixcook11/hello-server:1.0.0
        imagePullPolicy: Always
        name: echo-v1
        ports:
        - containerPort: 8080
        resources: {}
status:
  blueGreen: {}
  canary: {}
